/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.stellarsunset.semver;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.problems.ProblemReporter;
import org.gradle.api.problems.Problems;
import org.gradle.process.ExecOperations;

import javax.inject.Inject;

import static java.util.Objects.requireNonNull;

@SuppressWarnings("UnstableApiUsage")
public class AutoSemverPlugin implements Plugin<Project> {

    private static final Version.Serde JAVA = Version.Serde.java();

    private final ExecOperations execOperations;
    private final ProblemReporter problemReporter;

    @Inject
    public AutoSemverPlugin(ExecOperations execOperations, Problems problems) {
        this.execOperations = requireNonNull(execOperations);
        this.problemReporter = requireNonNull(problems).getReporter();
    }

    @Override
    public void apply(Project project) {
        var tasks = project.getTasks();

        Git git = new Git(project.getProjectDir(), execOperations, problemReporter);

        Version version = git.version();
        project.setVersion(JAVA.serialize(version));

        tasks.register("release", ReleaseTask.class, git)
                .configure(task -> task.setVersion(version));
    }
}
