/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.stellarsunset.semver;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AutoSemverPluginTest {
    @Test
    void pluginRegistersCorrectTasks(@TempDir File projectDir) {

        Project project = ProjectBuilder.builder()
                .withProjectDir(projectDir)
                .build();

        GitHelpers.initializeProjectSafely(projectDir);

        project.getPlugins().apply("io.github.stellarsunset.auto-semver");
        assertNotNull(project.getTasks().findByName("release"));
    }
}
