/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.stellarsunset.semver;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AutoSemverPluginTest {
    @Test
    void pluginRegistersCorrectTasks() {

        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("io.github.stellarsunset.auto-semver");

        assertAll(
                () -> assertNotNull(project.getTasks().findByName("setVersion")),
                () -> assertNotNull(project.getTasks().findByName("release"))
        );
    }
}
