/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.stellarsunset.semver;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.revwalk.RevCommit;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.UnexpectedBuildFailure;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AutoSemverPluginFunctionalTest {

    @Test
    void testNotAGitDirectory(@TempDir File projectDir) throws IOException {
        initializeProject(projectDir);
        assertThrows(AssertionError.class, () -> runGradle(projectDir, "showVersion"),
                "Show Version should fail, not a Git repository.");
    }

    @Test
    void testSetVersion(@TempDir File projectDir) {
        try (Git git = initializeRepositorySafely(projectDir)) {
            BuildResult result = runGradle(projectDir, "showVersion");
            assertTrue(result.getOutput().contains("Project Version: 0.0.1"));
        }
    }

    @Test
    void testRelease(@TempDir File projectDir) {
        try (Git git = initializeRepositorySafely(projectDir)) {
            BuildResult release = runGradle(projectDir, "release", "-Pminor");
            assertTrue(release.getOutput().contains("release 0.1.0"));

            BuildResult version = runGradle(projectDir, "showVersion");
            assertTrue(version.getOutput().contains("Project Version: 0.1.0"));
        }
    }

    private BuildResult runGradle(File projectDir, String... arguments) {
        try {
            GradleRunner runner = GradleRunner.create();
            runner.forwardOutput();
            runner.withPluginClasspath();
            runner.withArguments(arguments);
            runner.withProjectDir(projectDir);
            return runner.build();
        } catch (UnexpectedBuildFailure e) {
            return Assertions.fail(String.format("Unexpected error running Gradle subprocess: %s", e.getMessage()), e);
        }
    }

    private Git initializeRepositorySafely(File projectDir) {
        try {
            return initializeRepository(projectDir);
        } catch (Exception e) {
            return Assertions.fail(e);
        }
    }

    /**
     * Initialize a new gradle project w/ plugin configured.
     */
    private void initializeProject(File projectDir) throws IOException {
        File buildFile = new File(projectDir, "build.gradle");

        String content = """
                plugins {
                  id('io.github.stellarsunset.auto-semver')
                }
                
                tasks.register("showVersion") {
                    inputs.property("version", project.version)
                    doLast {
                        println("Project Version: ${inputs.properties["version"]}")
                    }
                }
                """;

        writeString(buildFile, content);

        File settingsFile = new File(projectDir, "settings.gradle");
        writeString(settingsFile, "");
    }

    /**
     * Initialize and commit the initial configuration for our project as a git repository in the directory.
     */
    private Git initializeRepository(File projectDir) throws Exception {

        Git main = Git.init()
                .setGitDir(projectDir)
                .setInitialBranch("main")
                .call();

        initializeProject(projectDir);

        RevCommit commit = main.commit()
                .setAuthor("junit", "junit@autosemver.github.com")
                .setMessage("Initial Commit")
                .setAll(true)
                .call();

        return main;
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
